version: '2'
services:
    htmltox:
        build:
            context: ./
            dockerfile: ./Dockerfile
        container_name: htmltox
        ports:
            - "80"
            - "9222:9222"
        volumes:
            - ./app:/go/src/app
            - $HOME/repos/github.com/mkenney/go-chrome:/go/src/github.com/mkenney/go-chrome
        environment:
            - LOG_LEVEL=debug
        entrypoint: sh
        command:
            - '-cexu'
            #- 'cd /go/src/app && dep ensure -update && go build -o /go/bin/app && /go/bin/app'
            - 'cd /go/src/app && go build -o /go/bin/app && /go/bin/app'
