version: '2'
services:
    htmltox:
        build:
            context: ./
            dockerfile: ./Dockerfile
        container_name: htmltox
        ports:
            - "80"
        volumes:
            - ./src:/go/src/htmltox