[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.0"

[[constraint]]
  branch = "master"
  name = "github.com/mkenney/go-chrome"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"
